#!/usr/bin/env php
<?php

define('BASE_DIR', __DIR__);

require_once 'vendor/autoload.php';     

use ConsoleTool\Console\SalaryCli;
use ConsoleTool\Exceptions\CommandException;

$console = new SalaryCli();

try {
    $console->init(array_slice($argv, 1));
    $console->run();
} catch (CommandException $e){
    echo $e->getMessage();
    exit($e->getCode());
}
